### ISSUE TITLE
Figure out which APIs we will be using

### ISSUE THREAD

**Issue by Bootsbigenough** [Bootsbigenough/Covid-Tracking-US-CA#4]

**Comment by Benjamineidum** [comment]
https://covid-19-data.unstatshub.org/datasets/cases-country/api

Use for recovered, active cases, people hospitalized, mortality rate, deaths, and others

**Comment by Benjamineidum** [comment]
https://covid19tracker.ca/vaccinationtracker.html

https://api.covid19tracker.ca/summary

Canadian Vaccination Records

**Comment by Benjamineidum** [comment]
If Chris says that chart.js counts as an api and we get our fetch data from[ ](https://covid-193.p.rapidapi.com/statistics), we should be set with our two. It does say _at least_ two, so if we can add more if we see fit
